//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocalStore()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Logo { get; set; }
        public string Bio { get; set; }
        public short AverageScore { get; set; }
        public Nullable<System.DateTime> LastCalculationDateTime { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
