//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public System.Guid Id { get; set; }
        public string Comment { get; set; }
        public string SubmitDateTime { get; set; }
        public string SubmitIP { get; set; }
        public string SubmitLatitude { get; set; }
        public string SubmitLongitude { get; set; }
        public string IsConfirm { get; set; }
        public short Type { get; set; }
        public bool IsAnonymous { get; set; }
        public bool ToBlackList { get; set; }
    
        public virtual ScoreBand ScoreBand { get; set; }
        public virtual Reviewer Reviewer { get; set; }
        public virtual City City { get; set; }
        public virtual Country Location { get; set; }
        public virtual Business Business { get; set; }
        public virtual Tag Tags { get; set; }
    }
}
