//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public System.Guid Id { get; set; }
        public string TagName { get; set; }
    
        public virtual LocalStore LocalStore { get; set; }
        public virtual Category Category { get; set; }
    }
}
